require_relative '../lib/pieces/piece'
require_relative '../lib/pieces/slideable'
require_relative '../lib/pieces/stepable'
require_relative '../lib/pieces/null_piece'
require_relative '../lib/pieces/bishop'
require_relative '../lib/pieces/king'
require_relative '../lib/pieces/knight'
require_relative '../lib/pieces/pawn'
require_relative '../lib/pieces/queen'
require_relative '../lib/pieces/rook'

